"""Add Cascade

Revision ID: d0ddf2205ddf
Revises: 0c5908359b93
Create Date: 2025-06-11 00:52:41.025707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0ddf2205ddf'
down_revision: Union[str, None] = '0c5908359b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('brand', sa.String(length=50), nullable=False))
    op.add_column('cars', sa.Column('model', sa.String(length=50), nullable=False))
    op.alter_column('cars', 'year',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='extract(year from year)::integer')
    op.drop_constraint(op.f('cars_customer_id_fkey'), 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cars', 'name')
    op.alter_column('customers', 'phone_number',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('staff', 'phone_number',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'phone_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
    op.alter_column('customers', 'phone_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
    op.add_column('cars', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key(op.f('cars_customer_id_fkey'), 'cars', 'customers', ['customer_id'], ['id'])
    op.alter_column('cars', 'year',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('cars', 'model')
    op.drop_column('cars', 'brand')
    # ### end Alembic commands ###
